(() => {
  'use strict';
  const $ = (s) => document.querySelector(s);
  const canvas = $('#board'); const ctx = canvas.getContext('2d');
  const W = 10, H = 7, CELL = 90, STORE = 'silk-road-bastion:v1';
  const regions = [
    { name: '绿洲商路', palette: ['#cfa96c','#4c968b','#738b58'], perk: '市场本纪元首笔交易额外获得 2 钱币', event: '商队' },
    { name: '赤岩峡谷', palette: ['#ba7750','#d4b878','#8e7054'], perk: '石料资源点额外产出 1', event: '地鸣' },
    { name: '雾港遗址', palette: ['#8ba6a3','#527d83','#b8c2ae'], perk: '敌袭开始时随机敌军减速', event: '潮汐' },
    { name: '星砂高原', palette: ['#d8c794','#876f91','#a27658'], perk: '晶矿资源点额外产出 1', event: '星尘' }
  ];
  const buildings = {
    sawmill: { name: '商路伐场', cost: { coin: 2, stone: 1 }, color: '#5f7f52', desc: '每轮产出木材', glyph: '木' },
    quarry: { name: '石工营', cost: { coin: 2, wood: 1 }, color: '#7e7c74', desc: '每轮产出石料', glyph: '石' },
    market: { name: '驿市', cost: { wood: 2, coin: 4 }, color: '#b87948', desc: '加快钱币增长', glyph: '市' },
    ballista: { name: '机关弩塔', cost: { wood: 3, stone: 2, coin: 3 }, color: '#326e70', desc: '自动攻击来敌', glyph: '弩' },
    wall: { name: '石砌外墙', cost: { stone: 3, coin: 3 }, color: '#9c7556', desc: '提高城门耐久', glyph: '墙' }
  };
  const upgrades = [
    { id: 'trade', title: '商贸合约', text: '每座驿市额外提供 2 钱币，繁荣 +2', apply: s => { s.mods.trade = (s.mods.trade || 0) + 1; s.prosperity += 2; } },
    { id: 'gears', title: '机关校准', text: '机关弩塔伤害 +6', apply: s => { s.mods.gears = (s.mods.gears || 0) + 1; } },
    { id: 'masonry', title: '石工章法', text: '外墙额外提供 12 核心上限', apply: s => { s.mods.masonry = (s.mods.masonry || 0) + 1; s.coreMax += 12; s.core += 12; } },
    { id: 'scouts', title: '驼铃斥候', text: '下个纪元额外获得 2 次行动', apply: s => { s.mods.scouts = (s.mods.scouts || 0) + 1; } },
    { id: 'salvage', title: '遗迹拆解', text: '每座资源建筑在敌袭后额外产出 1', apply: s => { s.mods.salvage = (s.mods.salvage || 0) + 1; } },
    { id: 'repair', title: '后勤修缮', text: '每次敌袭结束修复核心 14', apply: s => { s.mods.repair = (s.mods.repair || 0) + 1; } }
  ];
  let meta = loadMeta(), state = null, selectedBuild = null, selectedMode = 'expedition', siegeTimer = null;
  function loadMeta(){ try { return JSON.parse(localStorage.getItem(STORE)) || { renown: 0, records: { expedition: 0, survival: 0 }, unlocked: [] }; } catch { return { renown: 0, records: { expedition: 0, survival: 0 }, unlocked: [] }; } }
  function saveMeta(){ localStorage.setItem(STORE, JSON.stringify(meta)); }
  function hash(str){ let h = 2166136261; for (const c of str) h = Math.imul(h ^ c.charCodeAt(0), 16777619); return h >>> 0; }
  function rng(seed){ let x = seed || 1; return () => ((x = (x + 0x6D2B79F5) | 0), ((x = Math.imul(x ^ x >>> 15, x | 1)) ^ x + Math.imul(x ^ x >>> 7, x | 61)) >>> 0) / 4294967296; }
  function pick(a, r){ return a[Math.floor(r() * a.length)]; }
  function availableRegions(){ return regions.filter(region => region.name !== '星砂高原' || meta.unlocked.includes('星砂高原')); }
  function createState(mode, seedText){ const seed = seedText || Math.random().toString(36).slice(2, 10).toUpperCase(); const r = rng(hash(seed)); const region = pick(availableRegions(), r); const s = { mode, seed, r, epoch: 1, phase: 'develop', actions: 6, core:100, coreMax:100, resources:{wood:7,stone:6,crystal:1,coin:6}, region, nodes:[], structures:[], enemies:[], mods:{}, prosperity:0, threat:1, log:[], kills:0, route:[], tutorial:0, player:{x:4,y:4}, moving:false }; generateMap(s); log(s, '远征队抵达 ' + region.name + '。'); log(s, region.perk); return s; }
  function generateMap(s){ const r = s.r; s.nodes = []; s.structures = []; s.player={x:4,y:4};s.moving=false; const center = {x:4,y:3,type:'core',name:'丝路核心',level:1}; s.structures.push(center); const all=[]; for(let y=0;y<H;y++) for(let x=0;x<W;x++) if(!(x===4&&y===3)&&!(x===4&&y===4)) all.push({x,y}); all.sort(()=>r()-.5); const count=9+Math.min(5,s.epoch); for(let i=0;i<count;i++){ const p=all.pop(); const type=pick(['wood','wood','stone','stone','crystal','coin','ruin'],r); s.nodes.push({...p,type,amount:type==='crystal'?1:2+Math.floor(r()*2)}); } }
  function log(s, msg){ s.log.unshift({msg, id: Date.now()+Math.random()}); if(s.log.length>10)s.log.pop(); }
  function start(){ state = createState(selectedMode, $('#seedInput').value.trim()); $('#startScreen').classList.add('hidden'); $('#playScreen').classList.remove('hidden'); render(); if(!meta.seenHelp) openHelp(); }
  function render(){ if(!state)return; $('#seedText').textContent=state.seed; $('#modeText').textContent=state.mode==='expedition'?'无尽远征':'原地守城'; $('#regionName').textContent=state.region.name; $('#epochLabel').textContent='第 '+state.epoch+' 纪元'; $('#phaseLabel').textContent=state.phase==='develop'?'发展期':state.phase==='siege'?'迎敌中':'选择强化'; $('#actionLabel').textContent=state.phase==='develop'?'还可行动 '+state.actions+' 次':'防御自动战斗'; for(const k of ['wood','stone','crystal','coin']) $('#'+k).textContent=state.resources[k]; $('#coreHp').textContent=Math.max(0,Math.ceil(state.core))+' / '+state.coreMax; $('#threatValue').textContent=state.threat; renderBuilds(); $('#modifierList').innerHTML=Object.keys(state.mods).length ? Object.entries(state.mods).map(([k,v])=>'<span><b>'+upgradeName(k)+'</b> '+v+'</span>').join('') : '<span>尚未获得强化</span>'; $('#log').innerHTML=state.log.map(x=>'<p>'+x.msg+'</p>').join(''); renderEnemyInfo(); renderGoal(); $('#advanceBtn').disabled=state.phase!=='develop'||state.moving; $('#advanceBtn').textContent=state.phase==='develop'?'开始迎敌':'正在迎敌'; $('#boardHint').textContent = state.phase==='develop' ? (state.moving?'角色正在前往目标。':selectedBuild?'已选 '+buildings[selectedBuild].name+'，点击地图空地建造。':'点击地图移动，资源会自动采集。点击已有建筑可升级。') : '防御正在自动攻击。城门被打破则本局结束。'; draw(); }
  function maxActions(){ return 6 + (state.mods.scouts||0)*2; }
  function upgradeName(id){ return (upgrades.find(x=>x.id===id)||{title:id}).title; }
  function renderBuilds(){ $('#buildList').innerHTML=Object.entries(buildings).map(([id,b])=>{const affordable=canPay(b.cost);const cost=costText(b.cost);return '<button class="build-btn '+(selectedBuild===id?'selected':'')+'" data-build="'+id+'" '+(state.phase!=='develop'||!affordable?'disabled':'')+'><span class="build-glyph">'+b.glyph+'</span><strong>'+b.name+'</strong><small>'+b.desc+'</small><small class="build-cost">'+cost+'</small></button>';}).join(''); }
  function costText(cost){ return Object.entries(cost).map(([k,v])=>k==='wood'?'木 '+v:k==='stone'?'石 '+v:k==='coin'?'币 '+v:'晶 '+v).join('  '); }
  function canPay(cost){ return Object.entries(cost).every(([k,v])=>state.resources[k]>=v); }
  function pay(cost){ Object.entries(cost).forEach(([k,v])=>state.resources[k]-=v); }
  function renderEnemyInfo(){ if(!state.enemies.length){ $('#enemyInfo').textContent=state.phase==='develop'?'预计 '+(3+state.epoch+Math.floor(state.threat/2))+' 名敌人':'敌人已清除'; return;} const traits=[...new Set(state.enemies.map(e=>e.trait))].filter(Boolean); $('#enemyInfo').innerHTML='<b>'+state.enemies.length+' 名来敌</b>'+(traits.length?'<br>'+traits.join('、'):''); }
  function renderGoal(){ let text='点击地图上的资源，采够材料。'; if(state.phase==='siege') text='观察战局，弩塔会自动攻击敌人。'; else if(state.phase==='choice') text='选择一项强化，准备下一纪元。'; else if(!state.structures.some(b=>b.type==='ballista')) text=state.tutorial===0?'先点击一个地图资源点。':'建造一座机关弩塔。'; else if(state.core<state.coreMax*.75) text='城门危险，建造或升级石砌外墙。'; else text='继续发育，准备好后点击“开始迎敌”。'; $('#goalText').textContent=text; }
  function draw(){ if(!state)return; const p=state.region.palette; ctx.clearRect(0,0,canvas.width,canvas.height); ctx.fillStyle=p[0];ctx.fillRect(0,0,canvas.width,canvas.height); for(let y=0;y<H;y++)for(let x=0;x<W;x++){ const ox=x*CELL,oy=y*CELL;ctx.fillStyle=(x+y)%2?'rgba(255,245,211,.12)':'rgba(106,60,36,.06)';ctx.fillRect(ox,oy,CELL,CELL);ctx.strokeStyle='rgba(73,69,50,.12)';ctx.strokeRect(ox,oy,CELL,CELL); } ctx.fillStyle=p[1];ctx.globalAlpha=.35;ctx.beginPath();ctx.ellipse(100,220,120,185,-.3,0,Math.PI*2);ctx.fill();ctx.fillStyle=p[2];ctx.beginPath();ctx.ellipse(720,110,220,90,.15,0,Math.PI*2);ctx.fill();ctx.globalAlpha=1;
    state.nodes.forEach(n=>drawNode(n)); state.structures.forEach(b=>drawStructure(b)); state.enemies.forEach(e=>drawEnemy(e)); drawPlayer(); }
  function cellCenter(x,y){return{x:x*CELL+CELL/2,y:y*CELL+CELL/2};}
  function drawNode(n){ const c=cellCenter(n.x,n.y), map={wood:'#617c48',stone:'#77756f',crystal:'#806390',coin:'#ad7a31',ruin:'#8f6752'}, label={wood:'木',stone:'石',crystal:'晶',coin:'币',ruin:'遗'};ctx.save();ctx.translate(c.x,c.y);ctx.fillStyle='rgba(245,239,223,.88)';ctx.beginPath();ctx.arc(0,0,28,0,Math.PI*2);ctx.fill();ctx.strokeStyle=map[n.type];ctx.lineWidth=5;ctx.stroke();ctx.fillStyle=map[n.type];ctx.font='900 18px sans-serif';ctx.textAlign='center';ctx.fillText(label[n.type],0,6);ctx.fillStyle='rgba(20,45,53,.9)';ctx.font='900 11px sans-serif';ctx.fillText('+'+n.amount,0,42);ctx.restore(); }
  function drawStructure(b){const c=cellCenter(b.x,b.y);ctx.save();ctx.translate(c.x,c.y);if(b.type==='core'){ctx.fillStyle='#1d4e54';ctx.beginPath();ctx.arc(0,0,34,0,Math.PI*2);ctx.fill();ctx.fillStyle='#e1be71';ctx.beginPath();ctx.arc(0,0,17,0,Math.PI*2);ctx.fill();ctx.fillStyle='#12343a';ctx.font='bold 13px sans-serif';ctx.textAlign='center';ctx.fillText('城门',0,4)}else{const bld=buildings[b.type];ctx.fillStyle=bld.color;ctx.fillRect(-28,-25,56,50);ctx.fillStyle='rgba(255,245,211,.78)';ctx.fillRect(-20,-17,40,13);ctx.fillStyle='#fff2d2';ctx.font='bold 17px sans-serif';ctx.textAlign='center';ctx.fillText(bld.glyph,0,10);ctx.fillStyle='rgba(20,45,53,.88)';ctx.fillRect(2,11,29,16);ctx.fillStyle='#fff2d2';ctx.font='900 10px sans-serif';ctx.fillText('Lv.'+(b.level||1),16,23)}ctx.restore();}
  function drawEnemy(e){const c=cellCenter(e.x,e.y);ctx.save();ctx.translate(c.x,c.y);ctx.fillStyle=e.kind==='raider'?'#a5493d':e.kind==='wing'?'#6c5b8d':'#7b5948';ctx.beginPath();ctx.arc(0,0,16,0,Math.PI*2);ctx.fill();if(e.trait==='护盾'){ctx.strokeStyle='#d4c67b';ctx.lineWidth=3;ctx.beginPath();ctx.arc(0,0,21,0,Math.PI*2);ctx.stroke();}ctx.fillStyle='#f2ead7';ctx.font='bold 10px sans-serif';ctx.textAlign='center';ctx.fillText(Math.ceil(e.hp),0,4);ctx.restore();}
  function drawPlayer(){if(!state.player)return;const c=cellCenter(state.player.x,state.player.y);ctx.save();ctx.translate(c.x,c.y);ctx.fillStyle='rgba(16,45,49,.24)';ctx.beginPath();ctx.ellipse(0,20,18,7,0,0,Math.PI*2);ctx.fill();ctx.fillStyle='#d9b45e';ctx.beginPath();ctx.arc(0,-5,15,0,Math.PI*2);ctx.fill();ctx.fillStyle='#1e5357';ctx.fillRect(-14,8,28,24);ctx.fillStyle='#f0dfbd';ctx.beginPath();ctx.arc(0,-8,8,0,Math.PI*2);ctx.fill();ctx.fillStyle='#a54f3d';ctx.fillRect(8,4,17,6);ctx.fillStyle='#f5ecd9';ctx.font='900 10px sans-serif';ctx.textAlign='center';ctx.fillText('行者',0,24);ctx.restore();}
  function interact(ev){ if(!state||state.phase!=='develop'||state.moving)return; const rect=canvas.getBoundingClientRect();const x=Math.floor((ev.clientX-rect.left)/rect.width*W),y=Math.floor((ev.clientY-rect.top)/rect.height*H);if(x<0||y<0||x>=W||y>=H)return; const node=state.nodes.find(n=>n.x===x&&n.y===y); const occupied=state.structures.find(n=>n.x===x&&n.y===y); movePlayerTo(x,y,()=>{if(node){collect(node);return;}if(selectedBuild&&!occupied){build(selectedBuild,x,y);return;}if(occupied&&occupied.type!=='core'){upgradeStructure(occupied);return;}log(state,selectedBuild?'这个位置已有建筑。':'角色移动到了这里。');render();});}
  function movePlayerTo(x,y,done){if(!state)return;state.moving=true;render();const timer=setInterval(()=>{if(!state){clearInterval(timer);return;}const p=state.player;if(p.x!==x)p.x+=Math.sign(x-p.x);else if(p.y!==y)p.y+=Math.sign(y-p.y);draw();if(p.x===x&&p.y===y){clearInterval(timer);state.moving=false;done();}},110);}
  function collect(node){if(state.actions<=0){log(state,'行动已耗尽，请开始迎敌。');render();return;}state.actions--;state.tutorial=Math.max(state.tutorial,1);let amount=node.amount; if(node.type==='ruin'){ const reward=pick(['coin','crystal'],state.r);state.resources[reward]+=node.amount;log(state,'遗迹拆解获得 '+node.amount+(reward==='coin'?' 钱币。':' 晶矿。'));}else{if(node.type==='stone'&&state.region.name==='赤岩峡谷')amount++;if(node.type==='crystal'&&state.region.name==='星砂高原')amount++;state.resources[node.type]+=amount;log(state,'采集 '+amount+resourceLabel(node.type)+'。');}state.nodes=state.nodes.filter(n=>n!==node);render(); if(state.actions===0)log(state,'行动耗尽，可以开始迎敌。');}
  function resourceLabel(k){return ({wood:' 木材',stone:' 石料',crystal:' 晶矿',coin:' 钱币'})[k]||'';}
  function build(id,x,y){const b=buildings[id];if(!canPay(b.cost)||state.actions<=0)return;pay(b.cost);state.actions--;state.structures.push({x,y,type:id,level:1});if(id==='wall'){const extra=22+(state.mods.masonry||0)*12;state.coreMax+=extra;state.core=Math.min(state.coreMax,state.core+extra);log(state,'外墙完工，城门耐久上限 +'+extra+'。');}else{state.prosperity++;log(state,b.name+'完工。');}if(id==='ballista')state.tutorial=Math.max(state.tutorial,2);selectedBuild=null;render();}
  function upgradeStructure(target){const base=buildings[target.type];const level=target.level||1;const cost=Object.fromEntries(Object.entries(base.cost).map(([k,v])=>[k,Math.ceil(v*(1+level*.65))]));if(!canPay(cost)){log(state,'升级 '+base.name+' 需要 '+costText(cost)+'。');render();return;}if(state.actions<=0){log(state,'行动已耗尽，请开始迎敌。');render();return;}pay(cost);state.actions--;target.level=level+1;if(target.type==='wall'){const extra=16+(state.mods.masonry||0)*8;state.coreMax+=extra;state.core=Math.min(state.coreMax,state.core+extra);}state.prosperity++;log(state,base.name+' 升到 '+target.level+' 级。');render();}
  function makeEnemies(){const r=state.r,count=3+state.epoch+Math.floor(state.threat/2), traits=[];if(state.epoch>=3)traits.push('护盾');if(state.epoch>=4)traits.push('掠夺');if(state.epoch>=5)traits.push('飞行');if(state.epoch>=6)traits.push('破坏');state.enemies=[];for(let i=0;i<count;i++){const trait=traits.length&&r()<.42?pick(traits,r):'';state.enemies.push({x:9,y:i%H,hp:20+state.epoch*8+Math.floor(r()*10),kind:trait==='飞行'?'wing':r()<.5?'raider':'brute',trait});} }
  function beginSiege(){if(state.phase!=='develop'||state.moving)return;state.phase='siege';state.tutorial=Math.max(state.tutorial,3);selectedBuild=null;makeEnemies();log(state,'敌袭开始。防线准备迎击。');render();siegeTimer=setInterval(siegeStep,800);}
  function siegeStep(){if(!state||state.phase!=='siege')return;let damage=state.structures.filter(x=>x.type==='ballista').reduce((sum,b)=>sum+(b.level||1),0)*(13+(state.mods.gears||0)*6);if(damage&&state.enemies.length){state.enemies.sort((a,b)=>a.hp-b.hp);state.enemies[0].hp-=damage;log(state,'机关弩塔造成 '+damage+' 伤害。');}for(const e of state.enemies){ if(e.hp<=0)continue; if(e.x>4)e.x-=e.trait==='飞行'?2:1;else {let hit=5+state.epoch*1.7;if(e.trait==='掠夺'){state.resources.coin=Math.max(0,state.resources.coin-1);log(state,'掠夺者夺走 1 钱币。');}if(e.trait==='破坏'){const targets=state.structures.filter(b=>b.type!=='core');if(targets.length){const target=pick(targets,state.r);state.structures=state.structures.filter(b=>b!==target);log(state,'破坏者摧毁了 '+buildings[target.type].name+'。');}}state.core-=hit;log(state,'敌军冲击城门，损失 '+Math.ceil(hit)+' 耐久。');e.hp=0;} }const before=state.enemies.length;state.enemies=state.enemies.filter(e=>e.hp>0);state.kills+=before-state.enemies.length;if(state.core<=0){endRun(false);return;}if(!state.enemies.length){clearInterval(siegeTimer);siegeTimer=null;afterSiege();return;}render();}
  function afterSiege(){const levels=(id)=>state.structures.filter(x=>x.type===id).reduce((sum,b)=>sum+(b.level||1),0);const extra=state.mods.salvage||0;state.resources.wood+=levels('sawmill')*(3+extra);state.resources.stone+=levels('quarry')*(3+extra);state.resources.coin+=levels('market')*(3+extra);if(state.region.name==='绿洲商路'&&levels('market'))state.resources.coin+=2;if(state.mods.repair){state.core=Math.min(state.coreMax,state.core+14*state.mods.repair);}log(state,'敌袭结束。生产建筑完成结算。');state.phase='choice';state.threat=1+Math.floor(state.epoch*.8)+Math.floor(state.prosperity/3); showUpgrade();render();}
  function showUpgrade(){const r=state.r,options=[...upgrades].sort(()=>r()-.5).slice(0,3);openModal('纪元强化','选择一项强化，决定下一段远征的发展方向。',options.map(u=>({title:u.title,text:u.text,action:()=>{u.apply(state);closeModal();if(state.mode==='expedition')showRoutes();else nextEpoch();}})));}
  function showRoutes(){const choices=availableRegions().filter(x=>x.name!==state.region.name).sort(()=>state.r()-.5).slice(0,3);openModal('选择迁营路线','不同区域拥有不同地形和规则。选择后会以新地图继续下一纪元。',choices.map(reg=>({title:reg.name,text:reg.perk,action:()=>{state.region=reg;state.route.push(reg.name);closeModal();nextEpoch();}})));}
  function nextEpoch(){state.epoch++;state.phase='develop';state.actions=maxActions();if(state.mode==='expedition')generateMap(state);else refillNodes();log(state,'进入第 '+state.epoch+' 纪元。');render();}
  function refillNodes(){const old=state.nodes;const r=state.r;for(let i=old.length;i<10;i++){let p;do{p={x:Math.floor(r()*W),y:Math.floor(r()*H)}}while(state.structures.some(b=>b.x===p.x&&b.y===p.y)||state.nodes.some(n=>n.x===p.x&&n.y===p.y)||(state.player.x===p.x&&state.player.y===p.y));state.nodes.push({...p,type:pick(['wood','stone','coin','crystal','ruin'],r),amount:2+Math.floor(r()*2)});} }
  function openModal(title,text,choices){$('#modalEyebrow').textContent=state.mode==='expedition'?'无尽远征':'极限守城';$('#modalTitle').textContent=title;$('#modalText').textContent=text;$('#modalChoices').innerHTML='';choices.forEach(c=>{const b=document.createElement('button');b.className='choice-btn';b.type='button';b.innerHTML='<strong>'+c.title+'</strong><span>'+c.text+'</span>';b.addEventListener('click',c.action);$('#modalChoices').appendChild(b);});$('#choiceModal').classList.remove('hidden');}
  function closeModal(){$('#choiceModal').classList.add('hidden');}
  function openHelp(){$('#helpModal').classList.remove('hidden');}
  function closeHelp(){meta.seenHelp=true;saveMeta();$('#helpModal').classList.add('hidden');}
  function endRun(victory){if(!state)return;clearInterval(siegeTimer);siegeTimer=null;const score=(state.epoch-1)*100+state.kills*7+state.prosperity*20;const key=state.mode;const record=meta.records[key]||0;meta.records[key]=Math.max(record,state.epoch-1);meta.renown+=Math.max(1,Math.floor(score/50));if(state.epoch>=3&&!meta.unlocked.includes('星砂高原'))meta.unlocked.push('星砂高原');saveMeta();const title=victory?'远征暂告一段落':'堡垒已失守';const text='你抵达第 '+state.epoch+' 纪元，击败 '+state.kills+' 名敌军，获得 '+Math.max(1,Math.floor(score/50))+' 商路声望。';openModal(title,text,[{title:'再开一局',text:'使用新的随机种子开始远征。',action:()=>{closeModal();$('#playScreen').classList.add('hidden');$('#startScreen').classList.remove('hidden');renderRecords();}}]);state=null;}
  function renderRecords(){const e=meta.records.expedition||0,s=meta.records.survival||0;$('#records').innerHTML='商路声望 '+meta.renown+'<br>最高纪元：无尽远征 '+e+'，极限守城 '+s;}
  function economyTick(){if(!state||!['develop','siege'].includes(state.phase))return;const income=1+state.structures.filter(b=>b.type==='market').reduce((sum,b)=>sum+(b.level||1),0);state.resources.coin+=income;$('#coin').textContent=state.resources.coin;}
  function keyboardMove(ev){if(!state||state.phase!=='develop'||state.moving||!['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','w','a','s','d','W','A','S','D'].includes(ev.key))return;const delta={ArrowUp:[0,-1],w:[0,-1],W:[0,-1],ArrowDown:[0,1],s:[0,1],S:[0,1],ArrowLeft:[-1,0],a:[-1,0],A:[-1,0],ArrowRight:[1,0],d:[1,0],D:[1,0]}[ev.key];const x=Math.max(0,Math.min(W-1,state.player.x+delta[0])),y=Math.max(0,Math.min(H-1,state.player.y+delta[1]));ev.preventDefault();movePlayerTo(x,y,()=>{const node=state.nodes.find(n=>n.x===x&&n.y===y);if(node)collect(node);else render();});}
  document.addEventListener('click',ev=>{const mode=ev.target.closest('[data-mode]');if(mode){selectedMode=mode.dataset.mode;document.querySelectorAll('.mode-choice').forEach(x=>x.classList.toggle('active',x===mode));$('#startGame').textContent=selectedMode==='expedition'?'开始远征':'开始守城';}const b=ev.target.closest('[data-build]');if(b&&state){selectedBuild=b.dataset.build;render();}});$('#startGame').addEventListener('click',start);$('#advanceBtn').addEventListener('click',beginSiege);$('#endRun').addEventListener('click',()=>endRun(true));$('#helpBtn').addEventListener('click',openHelp);$('#closeHelp').addEventListener('click',closeHelp);canvas.addEventListener('click',interact);document.addEventListener('keydown',keyboardMove);setInterval(economyTick,2500);renderRecords();
})();
